version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: agri-advisor-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: agri-advisor
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - agri-network

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agri-advisor-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/agri-advisor?authSource=admin
      JWT_SECRET: your-production-jwt-secret-change-this
      JWT_EXPIRES_IN: 7d
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      AGROMONITORING_API_KEY: ${AGROMONITORING_API_KEY}
      MAX_FILE_SIZE: 10485760
      UPLOAD_PATH: /app/uploads/
      BCRYPT_ROUNDS: 12
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - agri-network

  # Frontend React App (for development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: agri-advisor-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
      REACT_APP_ENVIRONMENT: development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - agri-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: agri-advisor-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - agri-network

volumes:
  mongodb_data:
  backend_uploads:
  redis_data:

networks:
  agri-network:
    driver: bridge
